#!/usr/bin/env node
/**
 * scripts/sync-sheet.js
 *
 * Pulls listing rows from a "Publish to web" CSV export of a Google Sheet
 * you control, and regenerates `src/data/listings.js` from them.
 *
 * WHY A PUBLISHED CSV INSTEAD OF SCRAPING A THIRD-PARTY SITE:
 * Scraping Dubizzle/Bayut programmatically means bypassing their bot
 * protection, which violates their Terms of Service. This script instead
 * reads data YOU (or your Kabayan group admins) maintain yourself in a
 * Google Sheet — a source you fully control and are authorized to publish.
 * That also happens to be the only realistic way to get Facebook Kabayan
 * group posts into this app at all, since those groups have no public feed.
 *
 * SETUP (see README.md "Keeping listings fresh" section for full steps):
 *   1. Create a Google Sheet with the header row described below.
 *   2. File -> Share -> Publish to web -> select the sheet/tab -> CSV -> Publish.
 *   3. Copy the published CSV URL.
 *   4. Set it as the SHEET_CSV_URL environment variable / repo secret.
 *
 * EXPECTED CSV HEADER ROW (case-insensitive, order doesn't matter):
 *   id, source, title, location, type, price, gender, dewaIncluded,
 *   wifiIncluded, metroStation, metroWalkMins, postedBy, postedVia,
 *   postedDaysAgo, notes
 *
 * BEHAVIOR:
 *   - If SHEET_CSV_URL is missing, or the fetch/parse fails, or zero valid
 *     rows are found, the script logs a clear warning and exits WITHOUT
 *     touching src/data/listings.js — your existing data stays live.
 *   - Only rows with the required minimum fields (id, title, location,
 *     type, price) are kept; malformed rows are skipped with a warning,
 *     not a crash.
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from 'csv-parse/sync'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = path.join(__dirname, '..', 'src', 'data', 'listings.js')

const VALID_LOCATIONS = ['Deira', 'Al Karama', 'Al Satwa', 'Bur Dubai']
const VALID_TYPES = ['Lower Bunk', 'Upper Bunk', 'Solo Partition']
const MIN_PRICE = 500
const MAX_PRICE = 1500

function toBool(value, fallback = false) {
  if (value === undefined || value === null || value === '') return fallback
  const v = String(value).trim().toLowerCase()
  if (['true', 'yes', 'y', '1', 'included'].includes(v)) return true
  if (['false', 'no', 'n', '0', 'separate', 'not included'].includes(v)) return false
  return fallback
}

function toInt(value, fallback = 0) {
  const n = parseInt(String(value).replace(/[^\d-]/g, ''), 10)
  return Number.isFinite(n) ? n : fallback
}

/** Normalize a raw CSV row into our listing shape, or return null if invalid. */
function normalizeRow(row, rowIndex) {
  // csv-parse gives us header-keyed objects; keys may have inconsistent case
  // from manual sheet editing, so build a lowercase-keyed lookup first.
  const get = (name) => {
    const key = Object.keys(row).find((k) => k.trim().toLowerCase() === name.toLowerCase())
    return key ? String(row[key] ?? '').trim() : ''
  }

  const id = get('id') || `sheet-row-${rowIndex}`
  const title = get('title')
  const location = get('location')
  const type = get('type')
  const priceRaw = get('price')

  if (!title || !location || !type || !priceRaw) {
    console.warn(`⚠️  Skipping row ${rowIndex}: missing one of title/location/type/price.`)
    return null
  }

  const price = toInt(priceRaw)
  if (!price || price < MIN_PRICE || price > MAX_PRICE) {
    console.warn(
      `⚠️  Skipping row ${rowIndex} ("${title}"): price ${priceRaw} is outside ${MIN_PRICE}-${MAX_PRICE} AED budget range.`
    )
    return null
  }

  if (!VALID_LOCATIONS.includes(location)) {
    console.warn(
      `⚠️  Skipping row ${rowIndex} ("${title}"): location "${location}" is not one of ${VALID_LOCATIONS.join(', ')}.`
    )
    return null
  }

  if (!VALID_TYPES.includes(type)) {
    console.warn(
      `⚠️  Skipping row ${rowIndex} ("${title}"): type "${type}" is not one of ${VALID_TYPES.join(', ')}.`
    )
    return null
  }

  return {
    id,
    source: get('source') || 'Facebook (Kabayan Group)',
    title,
    location,
    type,
    price,
    gender: get('gender') || 'Any',
    dewaIncluded: toBool(get('dewaincluded'), false),
    wifiIncluded: toBool(get('wifiincluded'), false),
    metroStation: get('metrostation') || 'Verify with landlord',
    metroWalkMins: toInt(get('metrowalkmins'), 0),
    postedBy: get('postedby') || 'Verify with landlord',
    postedVia: get('postedvia') || 'Google Sheet (manual curation)',
    postedDaysAgo: toInt(get('posteddaysago'), 0),
    notes: get('notes') || ''
  }
}

function generateFileContents(listings) {
  const timestamp = new Date().toISOString()
  return `// AUTO-GENERATED by scripts/sync-sheet.js on ${timestamp}
// Do not hand-edit this array directly — edit the source Google Sheet instead
// (see README.md "Keeping listings fresh") and let the daily GitHub Action
// regenerate this file. SOURCES/LOCATIONS/ROOM_TYPES below are the app's
// fixed taxonomy and are safe to edit by hand if you add new categories.

export const SOURCES = {
  DUBIZZLE: 'Dubizzle',
  BAYUT: 'Bayut',
  FACEBOOK_KABAYAN: 'Facebook (Kabayan Group)'
}

export const LOCATIONS = ${JSON.stringify(VALID_LOCATIONS)}

export const ROOM_TYPES = ${JSON.stringify(VALID_TYPES)}

export const LISTINGS = ${JSON.stringify(listings, null, 2)}
`
}

async function main() {
  const sheetUrl = process.env.SHEET_CSV_URL

  if (!sheetUrl) {
    console.warn(
      '⚠️  SHEET_CSV_URL is not set. Skipping sync — keeping existing src/data/listings.js untouched.'
    )
    return
  }

  console.log(`Fetching listings CSV from: ${sheetUrl}`)

  let csvText
  try {
    const res = await fetch(sheetUrl)
    if (!res.ok) {
      throw new Error(`HTTP ${res.status} ${res.statusText}`)
    }
    csvText = await res.text()
  } catch (err) {
    console.error(`❌ Failed to fetch sheet CSV: ${err.message}`)
    console.error('   Keeping existing src/data/listings.js untouched.')
    return
  }

  let rows
  try {
    rows = parse(csvText, {
      columns: true,
      skip_empty_lines: true,
      trim: true
    })
  } catch (err) {
    console.error(`❌ Failed to parse CSV: ${err.message}`)
    console.error('   Keeping existing src/data/listings.js untouched.')
    return
  }

  if (!rows.length) {
    console.warn('⚠️  Sheet returned zero rows. Keeping existing src/data/listings.js untouched.')
    return
  }

  const listings = rows
    .map((row, i) => normalizeRow(row, i + 2)) // +2: header row + 1-indexing
    .filter(Boolean)
    .sort((a, b) => a.price - b.price)

  if (!listings.length) {
    console.warn(
      '⚠️  No valid listings survived validation. Keeping existing src/data/listings.js untouched.'
    )
    return
  }

  const fileContents = generateFileContents(listings)
  await fs.writeFile(OUTPUT_PATH, fileContents, 'utf-8')

  console.log(`✅ Wrote ${listings.length} listings to ${path.relative(process.cwd(), OUTPUT_PATH)}`)
}

main().catch((err) => {
  // Last-resort safety net: never let an unexpected error touch listings.js
  // or fail the whole workflow — just log it clearly.
  console.error('❌ Unexpected error in sync-sheet.js:', err)
  console.error('   Keeping existing src/data/listings.js untouched.')
})
